[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PackageManager"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "tomli-w==1.1.0",
    "virtualenv==20.28.0",
]

[project.scripts]
ppm = "PackageManager.main:main"